name: Provision Access

on:
  repository_dispatch:
    types: [jira-approval]

jobs:
  trigger-workato:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update Jira with workflow start
        run: |
          curl -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "body": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "🚀 GitHub workflow started for provisioning. Run ID: ${{ github.run_id }}"
                      }
                    ]
                  }
                ]
              }
            }' \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ github.event.client_payload.ticket_id }}/comment"
      
      - name: Trigger Workato Recipe
        id: workato
        run: |
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "ticket_id": "${{ github.event.client_payload.ticket_id }}",
              "request_type": "${{ github.event.client_payload.request_type }}",
              "user_email": "${{ github.event.client_payload.user_email }}",
              "github_run_id": "${{ github.run_id }}"
            }' \
            "https://webhooks.workato.com/webhooks/rest/07345295-70e9-43a2-8015-4be741900739/github-action")
          
          # Extract status code from response
          status_code="${response: -3}"
          echo "status_code=$status_code" >> $GITHUB_OUTPUT
          
          # Check if request was successful (2xx status codes)
          if [[ $status_code -ge 200 && $status_code -lt 300 ]]; then
            echo "outcome=success" >> $GITHUB_OUTPUT
          else
            echo "outcome=failure" >> $GITHUB_OUTPUT
          fi
      
      - name: Log Workato response
        run: echo "Workato response status - ${{ steps.workato.outputs.status_code }}"
      
      - name: Update Jira with workflow completion
        if: always()
        run: |
          # Determine status emoji and message based on outcome
          if [[ "${{ steps.workato.outputs.outcome }}" == "success" ]]; then
            emoji="✅"
            status_msg="completed successfully"
          else
            emoji="❌"
            status_msg="failed"
          fi
          
          curl -X POST \
            -H "Authorization: Basic ${{ secrets.JIRA_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"body\": {
                \"type\": \"doc\",
                \"version\": 1,
                \"content\": [
                  {
                    \"type\": \"paragraph\",
                    \"content\": [
                      {
                        \"type\": \"text\",
                        \"text\": \"$emoji GitHub workflow $status_msg. Workato has been triggered for provisioning.\"
                      }
                    ]
                  }
                ]
              }
            }" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ github.event.client_payload.ticket_id }}/comment"
