name: Provision Access

on:
  repository_dispatch:
    types: [jira-approval]

jobs:
  trigger-workato:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update Jira with workflow start
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ github.event.client_payload.ticket_id }}/comment
          method: 'POST'
          customHeaders: '{"Authorization": "Basic ${{ secrets.api_token }}", "Content-Type": "application/json"}'
          data: |
            {
              "body": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "🚀 GitHub workflow started for provisioning. Run ID: ${{ github.run_id }}"
                      }
                    ]
                  }
                ]
              }
            }
      
      - name: Trigger Workato Recipe
        id: workato
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://webhooks.workato.com/webhooks/rest/07345295-70e9-43a2-8015-4be741900739/github-action
          method: 'POST'
          data: |
            {
              "ticket_id": "${{ github.event.client_payload.ticket_id }}",
              "request_type": "${{ github.event.client_payload.request_type }}",
              "user_email": "${{ github.event.client_payload.user_email }}",
              "github_run_id": "${{ github.run_id }}"
            }
      
      - name: Log Workato response
        run: echo "Workato response status - ${{ steps.workato.outputs.status }}"
      
      - name: Update Jira with workflow completion
        if: always()
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ github.event.client_payload.ticket_id }}/comment
          method: 'POST'
          customHeaders: '{"Authorization": "Basic ${{ secrets.JIRA_AUTH_TOKEN }}", "Content-Type": "application/json"}'
          data: |
            {
              "body": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "${{ steps.workato.outcome == 'success' && '✅' || '❌' }} GitHub workflow completed with status: ${{ steps.workato.outcome }}. Workato has been triggered for provisioning."
                      }
                    ]
                  }
                ]
              }
            }
